// <auto-generated />
using AirportCodes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirportCodes.Migrations
{
    [DbContext(typeof(AirportCodesContext))]
    partial class AirportCodesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AirportCodes.Models.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BiggestAirline")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AirportId");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            AirportId = 1,
                            BiggestAirline = "Alaska Airlines",
                            City = "SeaTac, WA",
                            Code = "SEA",
                            Name = "Seattle-Tacoma International Airport"
                        },
                        new
                        {
                            AirportId = 2,
                            BiggestAirline = "Southwest Airlines",
                            City = "Portland, OR",
                            Code = "PDX",
                            Name = "Portland International Airport"
                        },
                        new
                        {
                            AirportId = 3,
                            BiggestAirline = "American Airlines",
                            City = "Los Angeles",
                            Code = "LAX",
                            Name = "Los Angeles International Airport"
                        },
                        new
                        {
                            AirportId = 4,
                            BiggestAirline = "American Airlines",
                            City = "Dallas, TX",
                            Code = "DFW",
                            Name = "Dallas/Fort Worth International Airport"
                        },
                        new
                        {
                            AirportId = 5,
                            BiggestAirline = "Delta",
                            City = " New York City, NY",
                            Code = "JFK",
                            Name = "John F. Kennedy International Airport"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
